# Generated by Django 5.2.13 on 2026-05-02 17:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('subjects', '0002_subject_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Оцінка (1-100)')),
                ('type', models.CharField(choices=[('current', 'Поточна'), ('module', 'Модульна'), ('exam', 'Іспит'), ('credit', 'Залік')], default='current', max_length=20, verbose_name='Тип оцінки')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата виставлення')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
