# Generated by Django 5.2.13 on 2026-05-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, default='Не вказано', max_length=100, verbose_name='Кафедра/Відділення'),
        ),
    ]
