# Generated by Django 5.2.13 on 2026-05-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('subjects', '0002_subject_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота'), (7, 'Неділя')], verbose_name='День тижня')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час закінчення')),
                ('room', models.CharField(max_length=50, verbose_name='Аудиторія')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекція'), ('practice', 'Практика'), ('lab', 'Лабораторна')], max_length=20, verbose_name='Тип заняття')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.group', verbose_name='Група')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Розклад',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
