# Generated by Django 5.2.13 on 2026-05-02 18:06

import assignments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('subjects', '0002_subject_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва завдання')),
                ('description', models.TextField(verbose_name='Опис завдання')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Максимальний бал')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=assignments.models.submission_path, verbose_name='Файл з відповіддю')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Текстова відповідь')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Час здачі')),
                ('status', models.CharField(choices=[('assigned', 'Призначено'), ('submitted', 'Здано'), ('checked', 'Перевірено')], default='submitted', max_length=15, verbose_name='Статус')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оцінка')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Завдання')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Здана робота',
                'verbose_name_plural': 'Здані роботи',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
