# Generated by Django 5.2.13 on 2026-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва групи')),
                ('faculty', models.CharField(max_length=150, verbose_name='Факультет')),
                ('year_formed', models.PositiveIntegerField(verbose_name='Рік формування')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
    ]
