# Generated by Django 5.2.13 on 2026-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва предмета')),
                ('credits', models.PositiveIntegerField(verbose_name='Кредити (ECTS)')),
                ('semester', models.PositiveIntegerField(verbose_name='Семестр')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-year_formed', 'name'], 'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
    ]
