# Generated by Django 5.2.13 on 2026-05-02 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('subjects', '0002_subject_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_present', models.BooleanField(default=True, verbose_name='Присутній')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина відсутності')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Відвідуваність',
                'verbose_name_plural': 'Відвідуваність',
                'ordering': ['-date', 'student__user__last_name'],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
